const dataEmployee = {
  status: [
    // { id: 1, name: "Lưu mới" },
    // { id: 2, name: "Chờ xử lý" },
    // { id: 3, name: "Chờ duyệt" },
    // { id: 4, name: "Yêu cầu bổ sung" },
    // { id: 5, name: "Đã duyệt" },
    // { id: 6, name: "Đã từ chối" },
    // { id: 8, name: "Chờ duyệt kết thúc" },
    // { id: 9, name: "Yêu cầu bổ sung đối với kết thúc" },
    // { id: 10, name: "Đã duyệt kết thúc" },
    // { id: 11, name: "Đã từ chối kết thúc" },
    // { id: 13, name: "Đã lưu hồ sơ" },
    // { id: 14, name: "Đã xóa" },
    { id: 1, name: "Tạo mới" },
    { id: 2, name: "Gửi lãnh đạo" },
    { id: 3, name: "Đã được chấp nhận" },
    { id: 4, name: "Yêu cầu bổ sung" },
    { id: 5, name: "Từ chối" },
    { id: 6, name: "Yêu cầu chấm dứt hồ sơ" },
    { id: 7, name: "Từ chối kết thúc hồ sơ" },
    { id: 8, name: "Hồ sơ đã được lưu" },
  ],
  gender: [
    { id: 1, name: "Nam" },
    { id: 2, name: "Nữ" },
    { id: 3, name: "Khác" },
  ],
  team: [
    { id: 1, name: "Nhóm 1" },
    { id: 2, name: "Nhóm 2" },
    { id: 3, name: "Nhóm 3" },
  ],
  relationship: [
    { id: 1, name: "Bố" },
    { id: 2, name: "Mẹ" },
    { id: 3, name: "Anh" },
    { id: 4, name: "Chị" },
    { id: 5, name: "Em" },
    { id: 6, name: "Cậu" },
    { id: 7, name: "Mợ" },
  ],
};

export default dataEmployee;
